force-app/main/default/objects/Account/fields/Q1_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Q1_Forecast__c</fullName>
    <label>Q1 Forecast</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Q2_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Q2_Forecast__c</fullName>
    <label>Q2 Forecast</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Q3_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Q3_Forecast__c</fullName>
    <label>Q3 Forecast</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Q4_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Q4_Forecast__c</fullName>
    <label>Q4 Forecast</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OpportunityForecastBuilder.cls
public with sharing class OpportunityForecastBuilder {
  public static void buildOpportunityForecast() {
    List<Opportunity> opps = [SELECT Id, Amount, CloseDate FROM Opportunity];

    OpportunityForecast forecast = new OpportunityForecast();

    for (Opportunity opp : opps) {
      forecast.addOpportunity(opp);
    }

    System.debug(forecast);
  }

  public static void buildOpportunityForecastByAccount() {
    List<Account> accounts = [
      SELECT Id, Name, (SELECT Id, Amount, CloseDate FROM Opportunities)
      FROM Account
    ];

    for (Account a : accounts) {
      OpportunityForecast forecast = new OpportunityForecast();
      for (Opportunity opp : a.Opportunities) {
        forecast.addOpportunity(opp);
      }
      System.debug('%%%% ' + a.Name);
      System.debug(forecast);

      a.Q1_Forecast__c = forecast.quarters.get(0).revenue;
      a.Q2_Forecast__c = forecast.quarters.get(1).revenue;
      a.Q3_Forecast__c = forecast.quarters.get(2).revenue;
      a.Q4_Forecast__c = forecast.quarters.get(3).revenue;
    }
    System.debug('++++++ ' + accounts);
    //update accounts;
  }
}